# This workflow will run tests using node and then publish a package to GitHub Container Registry and Docker Hub Registry when a pushed into main branches
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A

name: Continuous Integration

on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md
      - 'docs/**'
      - .github/workflows/docs.yml
      - .github/**.md # Templates

  pull_request:
    paths-ignore:
      - README.md
      - README.es.md
      - 'docs/**'
      - .github/workflows/docs.yml
      - .github/**.md # Templates

jobs:

  # Build dist application ADempiere-Vue
  build-app:
    name: Build Dist ADempiere-Vue
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Node configuration
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Enable https to install packages
        run: git config --global url."https://".insteadOf git://

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Install packages
        run: yarn ci

      - name: Run Linter
        run: yarn lint

      - name: Compile dist
        run: yarn build:prod

      - name: Upload dist app
        uses: actions/upload-artifact@v4  # Switch to Versión 4
        with:
          name: adempiere-vue
          path: dist
